# Generated by Django 5.2.7 on 2026-02-17 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(blank=True, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('PRINCIPAL', 'Principal'), ('DEAN', 'Dean'), ('HOD', 'HOD')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
