# Generated by Django 5.2.11 on 2026-03-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Template', max_length=200)),
                ('template_image', models.ImageField(upload_to='circular_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('content_top_margin', models.IntegerField(default=58, help_text='Top margin in mm where content area starts (below header/logo area)')),
                ('content_bottom_margin', models.IntegerField(default=45, help_text='Bottom margin in mm where content area ends (above signature area)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circular_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
