# Generated by Django 5.2.7 on 2026-02-17 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(blank=True, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('student_name', models.CharField(max_length=200)),
                ('college_email', models.CharField(blank=True, max_length=200, null=True)),
                ('register_number', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('academic_year_join', models.CharField(blank=True, max_length=10, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=5, null=True)),
                ('admission_quota', models.CharField(blank=True, max_length=50, null=True)),
                ('hosteller', models.BooleanField(default=False)),
                ('is_hosteller', models.BooleanField(default=False)),
                ('batch_year', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('first_graduate', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['roll_number'],
                'managed': False,
            },
        ),
    ]
