# Generated by Django 5.2.7 on 2026-02-19 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('batch_year', models.CharField(max_length=4)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('past', 'Past'), ('active', 'Active'), ('upcoming', 'Upcoming')], default='active', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'db_table': 'program_semesters',
                'ordering': ['batch_year', 'number'],
                'unique_together': {('department', 'batch_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
                ('program_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.programsemester')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SemesterSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_credits', models.IntegerField(default=0)),
                ('earned_credits', models.IntegerField(default=0)),
                ('arrear_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.programsemester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'semester_summaries',
                'ordering': ['student__roll_number'],
                'unique_together': {('student', 'program_semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('internal1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_sem_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Above Average'), ('C', 'Average'), ('U', 'Fail')], max_length=2, null=True)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'db_table': 'subject_results',
                'ordering': ['student__roll_number'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
