# Generated by Django 5.2.7 on 2026-02-26 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_programsemester_subject_semestersummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_uuid', models.CharField(max_length=50, unique=True)),
                ('document_type', models.CharField(choices=[('internal_marks', 'Internal Test Marks'), ('end_semester', 'End Semester Results'), ('attendance', 'Attendance Report'), ('other', 'Other Document')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('rag_collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_records_extracted', models.IntegerField(default=0)),
                ('total_students_processed', models.IntegerField(default=0)),
                ('total_subjects_processed', models.IntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
                ('program_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.programsemester')),
            ],
            options={
                'db_table': 'analyzed_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('marks', 'Marks/Grades'), ('attendance', 'Attendance'), ('other', 'Other Data')], max_length=20)),
                ('internal1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_sem_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='students.analyzeddocument')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'db_table': 'document_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGIndexMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=100, unique=True)),
                ('batch_id', models.CharField(max_length=50)),
                ('semester_id', models.CharField(max_length=50)),
                ('text_chunks_indexed', models.IntegerField(default=0)),
                ('images_indexed', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('index_created_at', models.DateTimeField(auto_now_add=True)),
                ('last_query_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_metadata', to='students.analyzeddocument')),
            ],
            options={
                'db_table': 'rag_index_metadata',
                'ordering': ['-index_created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyzeddocument',
            index=models.Index(fields=['department', 'program_semester'], name='analyzed_do_departm_c5af45_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzeddocument',
            index=models.Index(fields=['status'], name='analyzed_do_status_22573a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzeddocument',
            index=models.Index(fields=['is_indexed'], name='analyzed_do_is_inde_d583f8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentanalysisresult',
            index=models.Index(fields=['document', 'student'], name='document_an_documen_5807f2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentanalysisresult',
            index=models.Index(fields=['result_type'], name='document_an_result__ec4037_idx'),
        ),
        migrations.AddIndex(
            model_name='documentanalysisresult',
            index=models.Index(fields=['is_verified'], name='document_an_is_veri_e379e2_idx'),
        ),
    ]
