# Generated by Django 5.2.7 on 2026-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_pdf_analysis_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectresult',
            name='grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
