# Generated by Django 5.2.7 on 2026-02-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_subjectresult_grade_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='programsemester',
            options={'ordering': ['batch_year', 'semester__number']},
        ),
        migrations.AlterUniqueTogether(
            name='programsemester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programsemester',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='programsemester',
            unique_together={('semester', 'batch_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'semester', 'code')},
        ),
        migrations.RemoveField(
            model_name='programsemester',
            name='department',
        ),
        migrations.RemoveField(
            model_name='programsemester',
            name='name',
        ),
        migrations.RemoveField(
            model_name='programsemester',
            name='number',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program_semester',
        ),
    ]
