# Generated by Django 5.2.7 on 2026-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_semester_alter_programsemester_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsemester',
            name='batch_year',
            field=models.CharField(max_length=10),
        ),
    ]
