# Generated by Django 5.2.7 on 2026-02-17 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(blank=True, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('salutation', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('staff_code', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('official_email', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
